// The overlay guide: a spotlight tour of the whole journey, from authoring a
// rule through review, the gate, publish, deploy, the regime moving, and the
// loop closing. Steps navigate the real screens; targets are data-tour
// attributes. Practice roles get the full walk; a tenant admin gets the
// portal walk. Nothing here touches data.

import { useCallback, useEffect, useRef, useState } from 'react';
import { Button } from './primitives.tsx';
import type { User } from './api.ts';

export interface TourStep {
  route: string;
  target?: string; // data-tour attribute; absent = centred card
  title: string;
  body: string;
}

const PRACTICE_TOUR: TourStep[] = [
  {
    route: 'authoring',
    title: 'Lightsaber Backoffice',
    body:
      'This is the forge behind the seam: the corpus of regulatory rules, scoring signals, objections and messaging that grounds every sales artifact the skill produces. The database is the source of truth; the markdown bundle the skill reads is a build artifact, regenerated byte-for-byte on every publish. This tour walks the whole journey. Esc leaves it at any point.',
  },
  {
    route: 'authoring',
    target: 'user-switcher',
    title: 'Four desks, one discipline',
    body:
      'R. Hale authors substance. A. Okafor is the second pair of eyes; nothing substantive activates without a reviewer who is not its author. M. Brennan runs releases and the fleet. J. Park runs mechanics and can never approve substance. Switch identities here as the tour mentions them.',
  },
  {
    route: 'authoring',
    target: 'seam-pill',
    title: 'The published seam',
    body:
      'The version the fleet can be pinned to right now. Everything you will see funnels toward moving this number safely: nothing reaches it without two humans and a green gate.',
  },
  {
    route: 'authoring',
    target: 'rule-picker',
    title: '01 · Authoring',
    body:
      'Pick any rule to read or revise it, or start a new one. References allocate themselves: give a topic code and the system files the rule to convention, numbered in sequence across its regime family. You never compose an ID by hand.',
  },
  {
    route: 'authoring',
    target: 'form',
    title: 'Substance first',
    body:
      'The form reads the way a lawyer works: what the rule says (Statement, Buyer reading), what it rests on (Authority, sources), where and when it applies (jurisdiction, regime, the facts the engine needs). Jurisdiction and regime constrain each other: FCA will not pair with an EU-only tag.',
  },
  {
    route: 'authoring',
    target: 'review-panel',
    title: 'The gate starts at the keyboard',
    body:
      'Lint and structural checks run as you type: voice kill-list, em dashes, missing authority, unknown facts, footprint mismatches. A flag blocks submission until cleared, auto-resolved, or kept with a recorded reason. The same checks run again at submission and at the release gate, so nothing slips through a stale browser.',
  },
  {
    route: 'authoring',
    target: 'assist',
    title: 'The assistant drafts; it never approves',
    body:
      'Research returns sources to read yourself; for regulatory work it deliberately withholds drafted conclusions so the judgment stays yours. A source-less candidate is discarded server-side. Anything you accept arrives as a normal draft marked ai-assisted, and it cannot go for review until you have ticked every source as read. Scaffold shapes mechanics around your rough text without touching your words.',
  },
  {
    route: 'authoring',
    target: 'actions',
    title: 'Save, then submit',
    body:
      'Drafts are private to you until submitted. An unchanged submission is rejected as a no-op. Submission freezes the content under a hash; the approval that follows binds to exactly those bytes.',
  },
  {
    route: 'review',
    target: 'queue-card',
    title: '02 · Review',
    body:
      'The second human. A reviewer approves into the next candidate or returns with notes; the author of a version never reviews their own work, and the database enforces it independently of this screen. Tenant claims queue here too: same rule, same lint. Pre-screen asks the assistant three advisory questions (authority checkable? statement over-reach? advice drift?) and records that the reviewer saw the answer.',
  },
  {
    route: 'releases',
    target: 'publish-bar',
    title: '05 · The release gate',
    body:
      'A candidate freezes the approved versions, the document state and the eval suite at assembly. Five checks must pass: the eval suite, citation integrity, grounding, voice lint, coverage-paired evals. Publish on red does not exist: the state machine in the database has no such transition. It caught a real defect on day one — the shipped corpus cited a retired rule from an eval.',
  },
  {
    route: 'releases',
    target: 'gate-checks',
    title: 'Every check, every case',
    body:
      'Expand a check to see its cases. Evals are authored by humans only; the assistant has no eval-writing capability, so a drafted rule can never bend the test meant to catch it.',
  },
  {
    route: 'releases',
    target: 'changelog',
    title: 'What a release says about itself',
    body:
      'Added, changed, staled, re-authored, retired, by rule ID. Published releases are immutable and reproduce byte-for-byte forever; an artifact cites a release version and audit reads those pinned bytes, never the live rules.',
  },
  {
    route: 'tenants',
    target: 'fleet',
    title: '06 · The fleet',
    body:
      'Each adopter pins a published seam version. Freshness shows when the regime has moved under a pinned bundle; claims posture shows what their engine may assert. Provisioning creates an isolated claims space behind row-level security.',
  },
  {
    route: 'tenants',
    target: 'tenant-detail',
    title: 'Claims, deploys, upgrades',
    body:
      'A claim is one checkable sentence with evidence, reviewed like any substance. Deploying composes the pinned release with exactly this tenant’s claims, asserted in the transaction, checksummed, and keyed: the deploy key is the only credential a deployed skill holds, and it can only write abstention gaps. Upgrades show the diff first; superseded pins stay reproducible.',
  },
  {
    route: 'watch',
    target: 'watch-list',
    title: '03 · Regime Watch',
    body:
      'Movement notes arm watch items: a dated application, a bill in passage, an amendment pending publication. Mark the event occurred, or let the check pass fire date triggers and flag overdue re-verifies.',
  },
  {
    route: 'watch',
    target: 'watch-detail',
    title: 'One atomic act',
    body:
      'Triggering stales every dependent rule, opens a re-authoring task per rule, starts the SLA clocks for every pinned tenant, and builds the impact report: which rules, which releases, which tenants, which past artifacts cited them. Published history stays byte-stable; the staleness rides as an overlay on everything that ships next. Approving the re-author closes the task; publishing closes the loop.',
  },
  {
    route: 'coverage',
    target: 'matrix',
    title: '04 · Coverage',
    body:
      'Depth and freshness per jurisdiction and regime, with cells outside a regime’s footprint marked out of scope. The right-hand column is gap pressure: what live deals are abstaining on.',
  },
  {
    route: 'coverage',
    target: 'backlog',
    title: 'Demand-driven authoring',
    body:
      'Deployed skills log abstentions through a bounded schema; anything outside it, a firm name, an email, rejects by field name. The analyst triages; the backlog ranks by frequency times deal cost; a gap pulled into authoring closes automatically when its rule ships.',
  },
  {
    route: 'coverage',
    target: 'critic',
    title: 'The critic flags; it authors nothing',
    body:
      'Orphaned cross-references, jurisdiction layer asymmetries, bundled assertable units. Deterministic checks are reproducible run over run; semantic checks join when the assist model is configured. Every dismissal keeps its reason.',
  },
  {
    route: 'authoring',
    target: 'search',
    title: 'And the rest',
    body:
      '⌘K searches the corpus from anywhere. Defensibility reports reconstruct the exact rule text and authority an artifact rested on, as of the version it cited, and say whether each rule was human-authored or accepted from an assistant draft. Switch to D. Osei (once a tenant exists) to see the portal an adopter lives in. The PRDs and the issue list sit in /docs. That is the whole loop: author, review, gate, publish, deploy, watch, re-author.',
  },
];

const PORTAL_TOUR: TourStep[] = [
  {
    route: 'portal',
    title: 'Your seam',
    body:
      'This portal is your whole surface: the seam version your deployment runs, its freshness, your claims, and the audit trail. Your claims are yours alone; the shared corpus reaches you only through your deployed bundle.',
  },
  {
    route: 'portal',
    target: 'portal-claims',
    title: 'Claims: the only source of your facts',
    body:
      'The engine may assert your capabilities, certifications and figures only from claims approved here, each with evidence and a second pair of eyes. While this list is empty the engine abstains on all of it, which is honest output, not a defect.',
  },
  {
    route: 'portal',
    target: 'portal-defensibility',
    title: 'Defensibility on demand',
    body:
      'Give an artifact reference and the rules it cited; the report reconstructs the exact rule text and authority that was live in your pinned version, even after the live rules have moved. Mark a pull as tied to a closed deal and it feeds the success line.',
  },
  {
    route: 'portal',
    target: 'portal-gaps',
    title: 'What your deployment could not answer',
    body:
      'Every abstention your skill logs lands here at abstraction level, no prospect identity, and feeds the practice’s authoring backlog. Gaps close when the covering rule ships to you.',
  },
];

export function tourFor(actor: User | null): TourStep[] {
  return actor?.role === 'tenant_admin' ? PORTAL_TOUR : PRACTICE_TOUR;
}

const DONE_KEY = 'lsb_tour_done';
export const tourSeen = () => localStorage.getItem(DONE_KEY) === '1';
export const markTourSeen = () => localStorage.setItem(DONE_KEY, '1');

interface Rect {
  top: number;
  left: number;
  width: number;
  height: number;
}

export function Tour({
  steps,
  step,
  onStep,
  onClose,
  setRoute,
}: {
  steps: TourStep[];
  step: number;
  onStep: (n: number) => void;
  onClose: () => void;
  setRoute: (r: string) => void;
}) {
  const s = steps[step];
  const [rect, setRect] = useState<Rect | null>(null);
  const tries = useRef(0);

  const finish = useCallback(() => {
    markTourSeen();
    onClose();
  }, [onClose]);

  // Navigate, then find the target; screens load data, so retry briefly.
  useEffect(() => {
    setRoute(s.route);
    setRect(null);
    tries.current = 0;
    if (!s.target) return;
    let cancelled = false;
    const look = () => {
      if (cancelled) return;
      const el = document.querySelector(`[data-tour="${s.target}"]`);
      if (el) {
        const r = el.getBoundingClientRect();
        if (r.width > 0 || r.height > 0) {
          el.scrollIntoView({ block: 'nearest' });
          const r2 = el.getBoundingClientRect();
          setRect({ top: r2.top, left: r2.left, width: r2.width, height: r2.height });
          return;
        }
      }
      if (tries.current++ < 40) setTimeout(look, 100); // up to ~4s for data to land
    };
    look();
    return () => {
      cancelled = true;
    };
  }, [step, s.route, s.target, setRoute]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') finish();
      if (e.key === 'ArrowRight' && step < steps.length - 1) onStep(step + 1);
      if (e.key === 'ArrowLeft' && step > 0) onStep(step - 1);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [step, steps.length, onStep, finish]);

  const pad = 8;
  const spot = rect
    ? {
        top: rect.top - pad,
        left: rect.left - pad,
        width: rect.width + pad * 2,
        height: rect.height + pad * 2,
      }
    : null;

  // Card placement: below the spotlight when there is room, else above; centred when no target.
  const cardW = 420;
  let cardStyle: React.CSSProperties;
  if (spot) {
    const below = spot.top + spot.height + 16;
    const fitsBelow = below + 220 < window.innerHeight;
    cardStyle = {
      position: 'fixed',
      top: fitsBelow ? below : undefined,
      bottom: fitsBelow ? undefined : window.innerHeight - spot.top + 16,
      left: Math.max(16, Math.min(spot.left, window.innerWidth - cardW - 16)),
      width: cardW,
    };
  } else {
    cardStyle = { position: 'fixed', top: '24vh', left: '50%', transform: 'translateX(-50%)', width: 480 };
  }

  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 200 }}>
      {/* Backdrop: a dim wash, with a hole over the target when there is one. */}
      {spot ? (
        <div
          style={{
            position: 'fixed',
            top: spot.top,
            left: spot.left,
            width: spot.width,
            height: spot.height,
            borderRadius: 10,
            boxShadow: '0 0 0 9999px rgba(15, 23, 42, 0.45)',
            border: '1.5px solid var(--accent, #6366F1)',
            pointerEvents: 'none',
            transition: 'all 200ms ease',
          }}
        />
      ) : (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(15, 23, 42, 0.45)' }} onClick={finish} />
      )}

      <div
        style={{
          ...cardStyle,
          background: 'var(--white, #fff)',
          border: '1px solid var(--border)',
          borderRadius: 12,
          boxShadow: '0 24px 64px rgba(15,23,42,0.3)',
          padding: '18px 20px',
          zIndex: 201,
        }}
      >
        <div style={{ font: '600 10.5px/1 var(--font-sans)', letterSpacing: '0.09em', textTransform: 'uppercase', color: 'var(--accent-700, #4F46E5)', marginBottom: 8 }}>
          Step {step + 1} of {steps.length}
        </div>
        <div style={{ font: '600 15px/1.3 var(--font-sans)', color: 'var(--text-1)', marginBottom: 8 }}>{s.title}</div>
        <div style={{ font: '400 12.5px/1.65 var(--font-sans)', color: 'var(--text-2)', marginBottom: 14 }}>{s.body}</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Button variant="ghost" size="sm" onClick={finish}>
            {step === steps.length - 1 ? 'Close' : 'Skip tour'}
          </Button>
          <span style={{ flex: 1 }} />
          {step > 0 && (
            <Button variant="secondary" size="sm" onClick={() => onStep(step - 1)}>
              Back
            </Button>
          )}
          {step < steps.length - 1 ? (
            <Button variant="primary" size="sm" iconRight="arrowRight" onClick={() => onStep(step + 1)}>
              Next
            </Button>
          ) : (
            <Button variant="primary" size="sm" icon="check" onClick={finish}>
              Done
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}
